<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

# Exercise 1 recall

| Term       | Brief Description                                                                                                                                                                                                     |
|------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Subsetting | Subsetting is *selection*                                                                                                                                                                                             |
| Indexing   | Indexing is accessing *selecting* an element from the list or array by calling its position with [ ]. The first element has a index of zero, the last element can also be called without knowing the length using -1. |
| Slicing    | Slicing is accessing a few *selecting a range of* elements from the list or array [::], the default step is 1 but this can be changed.                                                                                |
| Masking    | This can only be done on NumPy arrays - the mask will show only the values that are true *or false, if using the bitwise operator ~*.                                                                                                                  |

# Exercise 2 Show the 'odd' letters

In [4]:
import numpy as np

In [5]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

In [18]:
np_array_2d[:,0] #subset all first elements

array(['1', '3', '2', '4', '5', '7', '6', '8', '10', '9'], dtype='<U21')

In [21]:
numbers = np_array_2d[:,0] #subset all first elements
numbers

array(['1', '3', '2', '4', '5', '7', '6', '8', '10', '9'], dtype='<U21')

In [24]:
integers = numbers.astype(int) #convert to integers
integers

array([ 1,  3,  2,  4,  5,  7,  6,  8, 10,  9])

In [32]:
remainder = integers%2 #remainder for division
remainder

array([1, 1, 0, 0, 1, 1, 0, 0, 0, 1])

In [35]:
mask = remainder == 1 #mask that checks if remainder is zero
mask

array([ True,  True, False, False,  True,  True, False, False, False,
        True])

In [40]:
letters = np_array_2d[mask]

In [44]:
letters

array([['1', 'A'],
       ['3', 'C'],
       ['5', 'E'],
       ['7', 'G'],
       ['9', 'I']], dtype='<U21')

In [46]:
letters[0]

array(['1', 'A'], dtype='<U21')

In [53]:
letters[:,1] #mask to extract the corresponding elements - 2nd dimension

array(['A', 'C', 'E', 'G', 'I'], dtype='<U21')