<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

# Comments

**What's good:** Most of the examples are alright.

**What's not good:** 

VS the python array only has letters
...a numpy array can only hold a single type of variable (eg float, letter, number)
In the example of code above these lines, yournp_array_2d was an array made up of a kind of element that is not necessarily letters or float values.

**Actionable:** Could you amend the text in the example above so that they match your code?

Good-to-know (Optional): NIL

In [2]:
import numpy as np

# What to expect in this chapter

It's very important to understand how to store, retrieve and modify data in programming.
- **influence how you think about data**
- ability to make algorithms to solve problems
- going from original data to final solution is affected by the form that you store your solution.

Ways to store and manipulate data eg:
1. List
2. Numpy arrrays
3. Dictionaries
4. Tuples

others: Applications - Data Processing - Data frames; Classes (advanced topic in nice)

# 1 Lists, Arrays & Dictionaries

## 1.1 Let’s compare

Dictionaries use a key and an associated value separated by a ':'. The dictionary very elegantly holds the real and superhero names in one structure while we need two lists (or arrays) for the same data.

For lists and arrays, the order matters. I.e. ‘Iron Man’ must be in the same position as ‘Tony Stark’ for things to work.

**Python lists**

In [6]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

**Numpy Arrays**

In [3]:
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

**Dictionaries**

In [4]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}

The problem you try to solve affects what you choose to store your data. Each has different functions.   
Lists and arrays offer features that dictionaries don't, and vice versa.

## 1.2 Accessing data from a list (or array)

A few things you can do: make a list, extract information or do calculations with the data.  
Python is a zero-indexed language, compared to R which starts at 1.
- this means it starts counting from 0.
- the first thing is the zeroth-index, so if you have 10 things in the list it will be numbered from 0-9

In [5]:
py_real_names[0]

'Natasha Romanoff'

In [7]:
py_super_names[0]

'Black Widow'

- data in 2 lists, correspondence is by position. to get both the names, put same index in both.

In [13]:
print(py_real_names[1], 'is', py_super_names[1])

Tony Stark is Iron Man


another way to do this is to use a variable to index, reusing rather than retyping it.  
- it is important to get the correspondence right.

In [12]:
i = 1
print(py_real_names[i], 'is', py_super_names[i])

Tony Stark is Iron Man


**reverse indexing** using a negative index to count from the back of the list
- using the index -1 will give the last element
- useful to access the last element without knowing list size (VS forward index, need to know size)

In [14]:
py_super_names[-1]

'Doctor Strange'

## 1.3 Accessing data from a dictionary

In [20]:
superhero_info["Natasha Romanoff"]

'Black Widow'

In [21]:
superhero_info["Black Widow"]

KeyError: 'Black Widow'

- dictionaries have a key-value structure
- "key" : "value"
- you cannot use the value to get the key

In [22]:
superhero_info.keys() #access all the keys

dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange'])

In [18]:
superhero_info.values() #access all the values

dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])

## 1.4 Higher dimensional lists

Instead of having 2 lists, can have a single 2D list (or array) to store the same information.  
This 2D list is a **list of lists**. [[]]
- Need to have an understanding: eg first item is real name, second item is superhero name

In [23]:
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]

# 2 Lists vs. Arrays

"one of the most annoying things to do with a list is indexing: getting things out of the list."  
This is where slicing and indexing is important.

Knowing the strengths and weaknesses of lists and arrays 
- Understanding the differences between list and arrays so you know which to use to store your data

In [3]:
py_list_2d = [
    [1, "A"], 
    [2, "B"], 
    [3, "C"], 
    [4, "D"],             
    [5, "E"], 
    [6, "F"], 
    [7, "G"], 
    [8, "H"],
    [9,  "I"], 
    [10, "J"]
    ]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array

In [30]:
py_list_2d

[[1, 'A'],
 [2, 'B'],
 [3, 'C'],
 [4, 'D'],
 [5, 'E'],
 [6, 'F'],
 [7, 'G'],
 [8, 'H'],
 [9, 'I'],
 [10, 'J']]

In [31]:
np_array_2d

array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C'],
       ['4', 'D'],
       ['5', 'E'],
       ['6', 'F'],
       ['7', 'G'],
       ['8', 'H'],
       ['9', 'I'],
       ['10', 'J']], dtype='<U21')

- lists have numbers and letters
- VS the python array only has letters

fundamental characteristic of a numpy array: can only hold a single type of variable (in this case, np_array_2d contains strings.)  

Lists can have combinations of different types of variables

- (np_array_2d is an array of an array of strings, because it is a 2d array)  
An array can hold a single type of other types of variables eg if there are a mix of floats and integers, the array will convert all the variables into integers since integers are a more general variable type, and floats can be converted to integers.  

## 2.1 Size

**Lists**

In [35]:
len(py_list_2d)

10

**Arrays**

In [33]:
len(np_array_2d)

10

In [34]:
np_array_2d.shape


(10, 2)

more information from arrays using shape.  
if the subarrays have different elements / not consistent size you will not get the size
- shape is not a function, it is a property/ attribute of NumPy arrays.

## 2.2 Arrays are fussy about type

- NumPy arrays only tolerate 1 type - be mindful of this when dealing with datasets with both number and text
- We easily change type (typecast) using the ‘hidden’ function astypes() 
  - covered in a later chapter

In [44]:
py_list = [1, 1.5, 'A']
np_array = np.array(py_list)

In [45]:
py_list

[1, 1.5, 'A']

In [43]:
np_array

array(['1', '1.5', 'A'], dtype='<U32')

## 2.3 Adding a number

In [47]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         # Reusing the Python list
                                     # to create a NEW
                                     # NumPy array

In [49]:
py_list

[1, 2, 3, 4, 5]

In [50]:
np_array

array([1, 2, 3, 4, 5])

**Arrays**

In [51]:
np_array + 100

array([101, 102, 103, 104, 105])

**Lists**

In [55]:
py_list + 100        # Won't work! cannot add number to elements in list

TypeError: can only concatenate list (not "int") to list

## 2.4 Adding another list

In [59]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

**Lists**

In [60]:
py_list_1 + py_list_2 #combine to give you a bigger lists

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

**Arrays**

In [58]:
np_array_1 + np_array_2 #individual elements are added

array([11, 22, 33, 44, 55])

for mathematical operations, use arrays. (cannot do math with lists)

## 2.5 Multiplying by a Number

In [61]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

**Lists**

In [66]:
py_list*2 #like adding the list together twice, causes list to grow

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

**Arrays**

In [67]:
np_array*2 #multiplies the elements by the number

array([ 2,  4,  6,  8, 10])

## 2.6 Squaring

**Array**

In [70]:
np_array**2

array([ 1,  4,  9, 16, 25])

**List**

In [74]:
py_list**2                      # doesn't work!  

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

## 2.7 Asking questions

In [75]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [80]:
py_list == 3     # Works, but what IS the question? not what you are asking

False

- never ask questions like this off a list - use arrays instead

In [78]:
np_array == 3 

array([False, False,  True, False, False])

In [82]:
np_array > 3  

array([False, False, False,  True,  True])

In [96]:
sum(np_array > 3) #powerful way to gifure out how many numbers greater than 3 eg if list was longer

2

## 2.8 Mathematics

In [98]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

**Lists**

In [86]:
sum(py_list)     # sum() is a base Python function

15

In [106]:
py_list.sum() #won't work, not defined for lists

AttributeError: 'list' object has no attribute 'sum'

In [87]:
max(py_list)     # max() is a base Python function

5

In [88]:
min(py_list)     # min() is a base Python function

1

**Arrays**

In [104]:
sum(np_array) #general python sum function, using this is slower than the other one using NumPy 

15

In [105]:
np_array.sum() #optimised sum function, faster

15

In [90]:
np_array.max()

5

In [91]:
np_array.min()

1

In [93]:
np_array.mean()

3.0

In [102]:
np_array.std()

1.4142135623730951

- (roughly speaking) an operation on a list works on the **whole list**.
- VS an operation on an array works on the **individual elements of the array**.

Lists can be very fast to grow, (VS array not fast to grow but fast to play with)
Arrays have the ability to do other math beyond sum, max and min. (since numpy is optimised for math)

- creating lists
- convert to array, do math
- can go back to list because faster to grow


# Exercises & Self-Assessment

In [ ]:



# Your solution here




## Footnotes